package demo.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentId
     *
     * @mbggenerated
     */
    private String commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.contentId
     *
     * @mbggenerated
     */
    private String contentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentDate
     *
     * @mbggenerated
     */
    private Date commentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.observerId
     *
     * @mbggenerated
     */
    private String observerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentDetail
     *
     * @mbggenerated
     */
    private String commentdetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentId
     *
     * @return the value of comment.commentId
     *
     * @mbggenerated
     */
    public String getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentId
     *
     * @param commentid the value for comment.commentId
     *
     * @mbggenerated
     */
    public void setCommentid(String commentid) {
        this.commentid = commentid == null ? null : commentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.contentId
     *
     * @return the value of comment.contentId
     *
     * @mbggenerated
     */
    public String getContentid() {
        return contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.contentId
     *
     * @param contentid the value for comment.contentId
     *
     * @mbggenerated
     */
    public void setContentid(String contentid) {
        this.contentid = contentid == null ? null : contentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentDate
     *
     * @return the value of comment.commentDate
     *
     * @mbggenerated
     */
    public Date getCommentdate() {
        return commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentDate
     *
     * @param commentdate the value for comment.commentDate
     *
     * @mbggenerated
     */
    public void setCommentdate(Date commentdate) {
        this.commentdate = commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.observerId
     *
     * @return the value of comment.observerId
     *
     * @mbggenerated
     */
    public String getObserverid() {
        return observerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.observerId
     *
     * @param observerid the value for comment.observerId
     *
     * @mbggenerated
     */
    public void setObserverid(String observerid) {
        this.observerid = observerid == null ? null : observerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentDetail
     *
     * @return the value of comment.commentDetail
     *
     * @mbggenerated
     */
    public String getCommentdetail() {
        return commentdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentDetail
     *
     * @param commentdetail the value for comment.commentDetail
     *
     * @mbggenerated
     */
    public void setCommentdetail(String commentdetail) {
        this.commentdetail = commentdetail == null ? null : commentdetail.trim();
    }
}