package demo.pojo;

public class ContentWithBLOBs extends Content {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.commentDetail
     *
     * @mbggenerated
     */
    private String contentdetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.commentIds
     *
     * @mbggenerated
     */
    private String commentids;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.commentDetail
     *
     * @return the value of content.commentDetail
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.commentIds
     *
     * @return the value of content.commentIds
     *
     * @mbggenerated
     */
    public String getCommentids() {
        return commentids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.commentIds
     *
     * @param commentids the value for content.commentIds
     *
     * @mbggenerated
     */
    public void setCommentids(String commentids) {
        this.commentids = commentids == null ? null : commentids.trim();
    }

	public String getContentdetail() {
		return contentdetail;
	}

	public void setContentdetail(String contentdetail) {
		this.contentdetail = contentdetail;
	}
}