package demo.pojo;

import java.util.Date;

public class User {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.userId
	 *
	 * @mbggenerated
	 */
	private String userid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.userName
	 *
	 * @mbggenerated
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.password
	 *
	 * @mbggenerated
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.phone
	 *
	 * @mbggenerated
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.email
	 *
	 * @mbggenerated
	 */
	private String email;

	private String roleid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.regTime
	 *
	 * @mbggenerated
	 */
	private Date regtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.userId
	 *
	 * @return the value of user.userId
	 *
	 * @mbggenerated
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.userId
	 *
	 * @param userid
	 *            the value for user.userId
	 *
	 * @mbggenerated
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.userName
	 *
	 * @return the value of user.userName
	 *
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.userName
	 *
	 * @param username
	 *            the value for user.userName
	 *
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.password
	 *
	 * @return the value of user.password
	 *
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.password
	 *
	 * @param password
	 *            the value for user.password
	 *
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.phone
	 *
	 * @return the value of user.phone
	 *
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.phone
	 *
	 * @param phone
	 *            the value for user.phone
	 *
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.email
	 *
	 * @return the value of user.email
	 *
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.email
	 *
	 * @param email
	 *            the value for user.email
	 *
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.regTime
	 *
	 * @return the value of user.regTime
	 *
	 * @mbggenerated
	 */
	public Date getRegtime() {
		return regtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.regTime
	 *
	 * @param regtime
	 *            the value for user.regTime
	 *
	 * @mbggenerated
	 */
	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	public String getRoleid() {
		return roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}
}