server:
  port: 8081
 
spring:
    datasource:
        name: demo
        url: jdbc:mysql://127.0.0.1:3306/xue
        username: root
        password: root123
        driver-class-name: com.mysql.jdbc.Driver
    mail:
      host: smtp.qq.com
      username: ******（QQ邮箱账号）
      password: ******（QQ邮箱中申请授权码）
      properties: 
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 
      pool.max-active: 8
      pool.max-wait: -1
      pool.max-idle: 8
      pool.min-idle: 0
      timeout: 500
      
      
       

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: demo.pojo


common:
  keyForAES: aeskey
  verifyCodeStr: 23456789ABCDEFGHJKLMNPQRSTUVWXYZ
  verifyCodeName: RANDOMVALIDATECODEKEY
  verifyCodeSwitch: true
  regSwitch: true
  
ueditor:
  config: config.json
  unified: true
  upload-path: D:\\uploadForJava\\
  url-prefix: http://localhost:8081/upload
  
sms:
  url: http://sms.91qxt.com/api/sms/index.php
  uid: （短信平台申请）
  username: （短信平台申请）
  token: （短信平台申请）
  appid: （短信平台申请）
  content: 您的注册验证码为：*，10分钟内有效，切勿将验证码泄露于他人。
  mailFrom: 1057150789@qq.com
  subject: 邮箱验证
