package demo.dao;

import java.util.List;

import demo.pojo.Content;
import demo.pojo.ContentWithBLOBs;

public interface ContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String contentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    int insert(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    int insertSelective(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    ContentWithBLOBs selectByPrimaryKey(String contentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Content record);
    
    List<ContentWithBLOBs> selectBySubmitterId(String submitterId);
    
    List<ContentWithBLOBs> findAllContent();
}