package demo.dao;

import java.util.List;

import demo.pojo.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated
	 */
	User selectByPrimaryKey(String userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(User record);

	User selectByName(String userName);

	List findAllRegUser();
}